/* **DON'T CHANGE THIS HEADER**
 $Author: Mike Lebson $
 $Revision: 1.2 $
 $Date: 2007/05/14 21:07:56 $
 $Source: /cvs/repo/Acquire/src/AboutFrame.java,v $
*/

public class AboutFrame extends javax.swing.JFrame
{
    public AboutFrame()
    {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        logoPanel = new LogoPanel();
        designedByLabel = new javax.swing.JLabel();
        ColinLabel = new javax.swing.JLabel();
        MikeLabel = new javax.swing.JLabel();
        MylesLabel = new javax.swing.JLabel();
        Acquire3MLabel = new javax.swing.JLabel();
        sunTradeMarkLabel1 = new javax.swing.JLabel();
        sunTradeMarkLabel2 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About the Game");
        logoPanel.setText("logoPanel");
        logoPanel.setBorderPainted(false);
        logoPanel.setFocusPainted(false);
        logoPanel.setRequestFocusEnabled(false);

        designedByLabel.setText("   Code designed and written by:");

        ColinLabel.setText(" Colin Hansen");

        MikeLabel.setText("Michael Lebson");

        MylesLabel.setText("and Myles Aylward");

        Acquire3MLabel.setFont(new java.awt.Font("Tahoma", 0, 10));
        Acquire3MLabel.setText("Acquire originally designed and created by 3M Games, 1962");

        sunTradeMarkLabel1.setFont(new java.awt.Font("Tahoma", 0, 10));
        sunTradeMarkLabel1.setText("Java and the Java Logo are trademarks or registered trademarks of");

        sunTradeMarkLabel2.setFont(new java.awt.Font("Tahoma", 0, 10));
        sunTradeMarkLabel2.setText("  Sun Microsystems, Inc. in the United States and other countries. ");

        okButton.setText("Ok");
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                okButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(Acquire3MLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sunTradeMarkLabel2)
                            .addComponent(sunTradeMarkLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MikeLabel)
                                            .addComponent(ColinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(MylesLabel)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(logoPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(designedByLabel))))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(designedByLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ColinLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MikeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MylesLabel)
                .addGap(20, 20, 20)
                .addComponent(Acquire3MLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sunTradeMarkLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sunTradeMarkLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseReleased
        dispose();
    }//GEN-LAST:event_okButtonMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Acquire3MLabel;
    private javax.swing.JLabel ColinLabel;
    private javax.swing.JLabel MikeLabel;
    private javax.swing.JLabel MylesLabel;
    private javax.swing.JLabel designedByLabel;
    private javax.swing.JButton logoPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel sunTradeMarkLabel1;
    private javax.swing.JLabel sunTradeMarkLabel2;
    // End of variables declaration//GEN-END:variables
}
