/* **DON'T CHANGE THIS HEADER**
 $Author: Mike Lebson $
 $Revision: 1.2 $
 $Date: 2007/05/14 21:07:56 $
 $Source: /cvs/repo/Acquire/src/HowToPlayPanel.java,v $
*/

public class HowToPlayPanel extends javax.swing.JPanel
{
    //*CONTRUCTOR*//

    public HowToPlayPanel()
    {
        initComponents();
    }

    //*OTHER METHODS*//

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        howToPlayLabel = new javax.swing.JLabel();
        howToPlay1 = new javax.swing.JLabel();
        howToPlay2 = new javax.swing.JLabel();
        howToPlay3 = new javax.swing.JLabel();
        howToPlay4 = new javax.swing.JLabel();
        howToPlay5 = new javax.swing.JLabel();
        howToPlay6 = new javax.swing.JLabel();
        howToPlay7a = new javax.swing.JLabel();
        howToPlay7b = new javax.swing.JLabel();
        howToPlay8a = new javax.swing.JLabel();
        howToPlay8b = new javax.swing.JLabel();
        howToPlay9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(575, 325));
        setMinimumSize(new java.awt.Dimension(575, 325));
        howToPlayLabel.setFont(new java.awt.Font("Tahoma", 0, 18));
        howToPlayLabel.setText("How To Play Acquire");

        howToPlay1.setFont(new java.awt.Font("Tahoma", 0, 12));
        howToPlay1.setText("To place a square, click on a highlighted box on the grid.");

        howToPlay2.setFont(new java.awt.Font("Tahoma", 0, 12));
        howToPlay2.setText("To form a company, place two squares adjacent to eachother.");

        howToPlay3.setFont(new java.awt.Font("Tahoma", 0, 12));
        howToPlay3.setText("To choose which company is formed/expanded select the company");

        howToPlay4.setFont(new java.awt.Font("Tahoma", 0, 12));
        howToPlay4.setText("To buy shares of an active company, click on the button that represents it.");

        howToPlay5.setFont(new java.awt.Font("Tahoma", 0, 12));
        howToPlay5.setText("To chat, type a message into the box at the bottom of the screen and click \"Chat\".");

        howToPlay6.setFont(new java.awt.Font("Tahoma", 0, 12));
        howToPlay6.setText("To drop an unplaceable square from your hand, click on it and click \"Yes\".");

        howToPlay7a.setFont(new java.awt.Font("Tahoma", 0, 12));
        howToPlay7a.setText("To end your turn, click the End Turn button or press the Space Bar.");

        howToPlay7b.setFont(new java.awt.Font("Tahoma", 0, 12));
        howToPlay7b.setText("(Turn may only be ended once a square has been placed)");

        howToPlay8a.setFont(new java.awt.Font("Tahoma", 0, 12));
        howToPlay8a.setText("To end the game, click the End Game button.");

        howToPlay8b.setFont(new java.awt.Font("Tahoma", 0, 12));
        howToPlay8b.setText("(See rules to see when End Game becomes enabled)");

        howToPlay9.setFont(new java.awt.Font("Tahoma", 0, 12));
        howToPlay9.setText("To start a new game, click New Game from the File menu.");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setText("from the dropdown menu and click \"OK\".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(howToPlayLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(howToPlay2)
                            .addComponent(howToPlay1)
                            .addComponent(howToPlay3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1))
                            .addComponent(howToPlay4)
                            .addComponent(howToPlay5)
                            .addComponent(howToPlay6)
                            .addComponent(howToPlay7a)
                            .addComponent(howToPlay8a)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(howToPlay7b))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(howToPlay8b))
                            .addComponent(howToPlay9))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(howToPlayLabel)
                .addGap(14, 14, 14)
                .addComponent(howToPlay1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(howToPlay2)
                .addGap(6, 6, 6)
                .addComponent(howToPlay3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(howToPlay4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(howToPlay5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(howToPlay6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(howToPlay7a)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(howToPlay7b)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(howToPlay8a)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(howToPlay8b)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(howToPlay9)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //*PRE-GENERATED FEILDS*//

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel howToPlay1;
    private javax.swing.JLabel howToPlay2;
    private javax.swing.JLabel howToPlay3;
    private javax.swing.JLabel howToPlay4;
    private javax.swing.JLabel howToPlay5;
    private javax.swing.JLabel howToPlay6;
    private javax.swing.JLabel howToPlay7a;
    private javax.swing.JLabel howToPlay7b;
    private javax.swing.JLabel howToPlay8a;
    private javax.swing.JLabel howToPlay8b;
    private javax.swing.JLabel howToPlay9;
    private javax.swing.JLabel howToPlayLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}