/* **DON'T CHANGE THIS HEADER**
 $Author: Mike Lebson $
 $Revision: 1.2 $
 $Date: 2007/05/14 21:07:56 $
 $Source: /cvs/repo/Acquire/src/RulesPanel.java,v $
*/

public class RulesPanel extends javax.swing.JPanel
{
    //*CONTRUCTOR*//

    public RulesPanel()
    {
        initComponents();
    }

    //*OTHER METHODS*//

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        rulesTitle = new javax.swing.JLabel();
        rules1a = new javax.swing.JLabel();
        rules1b = new javax.swing.JLabel();
        rules2 = new javax.swing.JLabel();
        rules3 = new javax.swing.JLabel();
        rules4 = new javax.swing.JLabel();
        rules5 = new javax.swing.JLabel();
        rules6 = new javax.swing.JLabel();
        rules7 = new javax.swing.JLabel();
        rules8 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(575, 325));
        setMinimumSize(new java.awt.Dimension(575, 325));
        rulesTitle.setFont(new java.awt.Font("Tahoma", 0, 18));
        rulesTitle.setText("Rules of Acquire");

        rules1a.setFont(new java.awt.Font("Tahoma", 0, 12));
        rules1a.setText("A player may only place squares that are in his/her hand.");

        rules1b.setFont(new java.awt.Font("Tahoma", 0, 12));
        rules1b.setText("(Placeable squares are highlighed on the grid)");

        rules2.setFont(new java.awt.Font("Tahoma", 0, 12));
        rules2.setText("A player may only place one square and buy 3 stocks per turn.");

        rules3.setFont(new java.awt.Font("Tahoma", 0, 12));
        rules3.setText("A player may only buy shares once a s/he has placed a square.");

        rules4.setFont(new java.awt.Font("Tahoma", 0, 12));
        rules4.setText("A company is formed when two squares are placed in adjacent squares.");

        rules5.setFont(new java.awt.Font("Tahoma", 0, 12));
        rules5.setText("A company becomes safe when it encompasses more than 10 squares.");

        rules6.setFont(new java.awt.Font("Tahoma", 0, 12));
        rules6.setText("Safe companies cannot merge with other safe companies.");

        rules7.setFont(new java.awt.Font("Tahoma", 0, 12));
        rules7.setText("All squares in between two safe companies become unplaceable.");

        rules8.setFont(new java.awt.Font("Tahoma", 0, 12));
        rules8.setText("Unplaceable squares in a player's hand may be dropped.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(rulesTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rules1a)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(rules1b))
                            .addComponent(rules2)
                            .addComponent(rules3)
                            .addComponent(rules7)
                            .addComponent(rules6)
                            .addComponent(rules8)
                            .addComponent(rules5)
                            .addComponent(rules4))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(rulesTitle)
                .addGap(32, 32, 32)
                .addComponent(rules1a)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rules1b)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rules2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rules3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rules4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rules5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rules6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rules7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rules8)
                .addGap(76, 76, 76))
        );
    }// </editor-fold>//GEN-END:initComponents

    //*PRE-GENERATED FEILDS*//

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel rules1a;
    private javax.swing.JLabel rules1b;
    private javax.swing.JLabel rules2;
    private javax.swing.JLabel rules3;
    private javax.swing.JLabel rules4;
    private javax.swing.JLabel rules5;
    private javax.swing.JLabel rules6;
    private javax.swing.JLabel rules7;
    private javax.swing.JLabel rules8;
    private javax.swing.JLabel rulesTitle;
    // End of variables declaration//GEN-END:variables
}